markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Victory Formation
url: http://lyzidiamond.com
description: Victory formation.
twitter: lyzidiamond
github: lyzidiamond
gravatar_url: http://gravatar.com/avatar/029f8c0e50e126f91562b126af9f22dd
